<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:52.
 */
class jqAutocompleteTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqAutocomplete
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqAutocomplete;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqAutocomplete::isNotACQuery
     * @todo   Implement testIsNotACQuery().
     */
    public function testIsNotACQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::getOption
     * @todo   Implement testGetOption().
     */
    public function testGetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::setEvent
     * @todo   Implement testSetEvent().
     */
    public function testSetEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::setSource
     * @todo   Implement testSetSource().
     */
    public function testSetSource() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::setLength
     * @todo   Implement testSetLength().
     */
    public function testSetLength() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::queryAutocomplete
     * @todo   Implement testQueryAutocomplete().
     */
    public function testQueryAutocomplete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqAutocomplete::renderAutocomplete
     * @todo   Implement testRenderAutocomplete().
     */
    public function testRenderAutocomplete() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
