<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:57.
 */
class jqCalendarTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqCalendar
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqCalendar;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqCalendar::getOption
     * @todo   Implement testGetOption().
     */
    public function testGetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqCalendar::setOption
     * @todo   Implement testSetOption().
     */
    public function testSetOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqCalendar::setEvent
     * @todo   Implement testSetEvent().
     */
    public function testSetEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqCalendar::renderCalendar
     * @todo   Implement testRenderCalendar().
     */
    public function testRenderCalendar() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
