<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:12.
 */
class jqChartTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqChart
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqChart;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqChart::getChartOptions
     * @todo   Implement testGetChartOptions().
     */
    public function testGetChartOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setChartOptions
     * @todo   Implement testSetChartOptions().
     */
    public function testSetChartOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setChartEvent
     * @todo   Implement testSetChartEvent().
     */
    public function testSetChartEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setColors
     * @todo   Implement testSetColors().
     */
    public function testSetColors() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setLabels
     * @todo   Implement testSetLabels().
     */
    public function testSetLabels() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setLanguage
     * @todo   Implement testSetLanguage().
     */
    public function testSetLanguage() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setLegend
     * @todo   Implement testSetLegend().
     */
    public function testSetLegend() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setLoading
     * @todo   Implement testSetLoading().
     */
    public function testSetLoading() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setPlotOptions
     * @todo   Implement testSetPlotOptions().
     */
    public function testSetPlotOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setSubtitle
     * @todo   Implement testSetSubtitle().
     */
    public function testSetSubtitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setTooltip
     * @todo   Implement testSetTooltip().
     */
    public function testSetTooltip() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setxAxis
     * @todo   Implement testSetxAxis().
     */
    public function testSetxAxis() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setyAxis
     * @todo   Implement testSetyAxis().
     */
    public function testSetyAxis() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setExporting
     * @todo   Implement testSetExporting().
     */
    public function testSetExporting() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setNavigation
     * @todo   Implement testSetNavigation().
     */
    public function testSetNavigation() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::addSeries
     * @todo   Implement testAddSeries().
     */
    public function testAddSeries() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setSeriesOption
     * @todo   Implement testSetSeriesOption().
     */
    public function testSetSeriesOption() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setJSCode
     * @todo   Implement testSetJSCode().
     */
    public function testSetJSCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::setTheme
     * @todo   Implement testSetTheme().
     */
    public function testSetTheme() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqChart::renderChart
     * @todo   Implement testRenderChart().
     */
    public function testRenderChart() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
