<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:56.
 */
class jqFormTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqForm
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqForm;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqForm::setConnection
     * @todo   Implement testSetConnection().
     */
    public function testSetConnection() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setColumnLayout
     * @todo   Implement testSetColumnLayout().
     */
    public function testSetColumnLayout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setUrl
     * @todo   Implement testSetUrl().
     */
    public function testSetUrl() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setTableStyles
     * @todo   Implement testSetTableStyles().
     */
    public function testSetTableStyles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setFormHeader
     * @todo   Implement testSetFormHeader().
     */
    public function testSetFormHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setFormFooter
     * @todo   Implement testSetFormFooter().
     */
    public function testSetFormFooter() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setPrimaryKeys
     * @todo   Implement testSetPrimaryKeys().
     */
    public function testSetPrimaryKeys() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::addElement
     * @todo   Implement testAddElement().
     */
    public function testAddElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::addEvent
     * @todo   Implement testAddEvent().
     */
    public function testAddEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::addGroup
     * @todo   Implement testAddGroup().
     */
    public function testAddGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::createElement
     * @todo   Implement testCreateElement().
     */
    public function testCreateElement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::createGroup
     * @todo   Implement testCreateGroup().
     */
    public function testCreateGroup() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setUploadOptions
     * @todo   Implement testSetUploadOptions().
     */
    public function testSetUploadOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setJSCode
     * @todo   Implement testSetJSCode().
     */
    public function testSetJSCode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::setAjaxOptions
     * @todo   Implement testSetAjaxOptions().
     */
    public function testSetAjaxOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::getPrimaryKeyId
     * @todo   Implement testGetPrimaryKeyId().
     */
    public function testGetPrimaryKeyId() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::insert
     * @todo   Implement testInsert().
     */
    public function testInsert() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::update
     * @todo   Implement testUpdate().
     */
    public function testUpdate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::save
     * @todo   Implement testSave().
     */
    public function testSave() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqForm::renderForm
     * @todo   Implement testRenderForm().
     */
    public function testRenderForm() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
