<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:11.
 */
class jqGridTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqGrid
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqGrid;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqGrid::logQuery
     * @todo   Implement testLogQuery().
     */
    public function testLogQuery() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::debugout
     * @todo   Implement testDebugout().
     */
    public function testDebugout() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::sendErrorHeader
     * @todo   Implement testSendErrorHeader().
     */
    public function testSendErrorHeader() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::buildSearch
     * @todo   Implement testBuildSearch().
     */
    public function testBuildSearch() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::getUserDate
     * @todo   Implement testGetUserDate().
     */
    public function testGetUserDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::setUserDate
     * @todo   Implement testSetUserDate().
     */
    public function testSetUserDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::getUserTime
     * @todo   Implement testGetUserTime().
     */
    public function testGetUserTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::setUserTime
     * @todo   Implement testSetUserTime().
     */
    public function testSetUserTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::getDbDate
     * @todo   Implement testGetDbDate().
     */
    public function testGetDbDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::setDbDate
     * @todo   Implement testSetDbDate().
     */
    public function testSetDbDate() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::getDbTime
     * @todo   Implement testGetDbTime().
     */
    public function testGetDbTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::setDbTime
     * @todo   Implement testSetDbTime().
     */
    public function testSetDbTime() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::getGridParams
     * @todo   Implement testGetGridParams().
     */
    public function testGetGridParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::setGridParams
     * @todo   Implement testSetGridParams().
     */
    public function testSetGridParams() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::selectLimit
     * @todo   Implement testSelectLimit().
     */
    public function testSelectLimit() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::queryGrid
     * @todo   Implement testQueryGrid().
     */
    public function testQueryGrid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::exportToExcel
     * @todo   Implement testExportToExcel().
     */
    public function testExportToExcel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::setPdfOptions
     * @todo   Implement testSetPdfOptions().
     */
    public function testSetPdfOptions() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::exportToPdf
     * @todo   Implement testExportToPdf().
     */
    public function testExportToPdf() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::exportToCsv
     * @todo   Implement testExportToCsv().
     */
    public function testExportToCsv() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::querySubGrid
     * @todo   Implement testQuerySubGrid().
     */
    public function testQuerySubGrid() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqGrid::addUserData
     * @todo   Implement testAddUserData().
     */
    public function testAddUserData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
