<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:58.
 */
class jqTreeGridTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqTreeGrid
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqTreeGrid;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqTreeGrid::setData
     * @todo   Implement testSetData().
     */
    public function testSetData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::setLeafData
     * @todo   Implement testSetLeafData().
     */
    public function testSetLeafData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::setTreeModel
     * @todo   Implement testSetTreeModel().
     */
    public function testSetTreeModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::getTreeModel
     * @todo   Implement testGetTreeModel().
     */
    public function testGetTreeModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::setTableConfig
     * @todo   Implement testSetTableConfig().
     */
    public function testSetTableConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::getTableConfig
     * @todo   Implement testGetTableConfig().
     */
    public function testGetTableConfig() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::getLeafNodes
     * @todo   Implement testGetLeafNodes().
     */
    public function testGetLeafNodes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::queryTree
     * @todo   Implement testQueryTree().
     */
    public function testQueryTree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::updateTreeNode
     * @todo   Implement testUpdateTreeNode().
     */
    public function testUpdateTreeNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::insertTreeNode
     * @todo   Implement testInsertTreeNode().
     */
    public function testInsertTreeNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::deleteTreeNode
     * @todo   Implement testDeleteTreeNode().
     */
    public function testDeleteTreeNode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::editTree
     * @todo   Implement testEditTree().
     */
    public function testEditTree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers jqTreeGrid::renderTree
     * @todo   Implement testRenderTree().
     */
    public function testRenderTree() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
