<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:13:54.
 */
class DatabaseTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Database
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Database;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Database::setUser
     * @todo   Implement testSetUser().
     */
    public function testSetUser() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::setTable
     * @todo   Implement testSetTable().
     */
    public function testSetTable() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::setDbType
     * @todo   Implement testSetDbType().
     */
    public function testSetDbType() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::setSearchs
     * @todo   Implement testSetSearchs().
     */
    public function testSetSearchs() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::newEvent
     * @todo   Implement testNewEvent().
     */
    public function testNewEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::editEvent
     * @todo   Implement testEditEvent().
     */
    public function testEditEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::moveEvent
     * @todo   Implement testMoveEvent().
     */
    public function testMoveEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::resizeEvent
     * @todo   Implement testResizeEvent().
     */
    public function testResizeEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::removeEvent
     * @todo   Implement testRemoveEvent().
     */
    public function testRemoveEvent() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Database::getEvents
     * @todo   Implement testGetEvents().
     */
    public function testGetEvents() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
