<?php

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2014-02-24 at 13:14:08.
 */
class jqEventLocalizationTest extends PHPUnit_Framework_TestCase {

    /**
     * @var jqEventLocalization
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new jqEventLocalization;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers jqEventLocalization::setDatepickerLang
     * @todo   Implement testSetDatepickerLang().
     */
    public function testSetDatepickerLang() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
